# environment.yaml

name: repro-brats
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - anaconda
  - pip
  - pip:
    - requests==2.31.0
    - ipywidgets==8.0.6
    - matplotlib==3.5.2
    - nibabel==4.0.2
    - numpy==1.21.5
    - pandas==1.5.1
    - parse==1.19.0
    - scipy==1.10.1